development:
  adapter: postgresql
  database: naafag_development
  encoding: utf8
  gssencmode: disable # Fix SolidQueue crash ~ https://github.com/rails/solid_queue/issues/669
  host: <%= ENV.fetch('DATABASE_HOST', '127.0.0.1') %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  username: postgres

# production:
#   adapter: postgresql
#   database: danca_production
#   encoding: utf8
#   gssencmode: disable # Fix SolidQueue crash ~ https://github.com/rails/solid_queue/issues/669
#   host: <%= ENV['DATABASE_HOST'] %>
#   password: <%= ENV['DATABASE_PASSWORD'] %>
#   pool: 100
#   username: <%= ENV['DATABASE_USERNAME'] %>

# test:
#   adapter: postgresql
#   database: danca_test<%= ENV.fetch('TEST_ENV_NUMBER', '') %>
#   encoding: utf8
#   gssencmode: disable # Fix SolidQueue crash ~ https://github.com/rails/solid_queue/issues/669
#   host: 127.0.0.1
#   password: <%= ENV['DATABASE_PASSWORD'] %>
#   username: postgres
